# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    git clone https://github.com/flutter/flutter.git -b stable
    ./flutter/bin/flutter doctor
    export PATH=./flutter/bin:$PATH
    flutter
  displayName: 'prepare flutter'

- script: |
    flutter build apk
  workingDirectory: ./gallery/gallery/
  displayName: 'Build'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Pipeline.Workspace)'
    publishLocation: 'pipeline'
