# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'macos-latest'
  
variables:
- group: PAT

steps:
- script: |
    git clone https://github.com/flutter/flutter.git -b master
    export PATH=$(Pipeline.Workspace)/s/flutter/bin:$PATH
    flutter doctor -v
    flutter config --enable-linux-desktop
    flutter config --enable-macos-desktop
    flutter config --enable-windows-desktop
    flutter config --enable-web
    cd experimental/desktop_photo_search
    flutter create .
    cd ..
    git add experimental/desktop_photo_search/
    git commit -m 'add all platforms[skip ci]'
    git push https://mehulagg:$(GITHUB_MEHULAGG)@github.com/flutter-ui-designs/samples.git HEAD:master
  displayName: 'All'
    
