# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: install-flutter-sdk@0
  inputs:
    channel: 'stable'
- script: |
    flutter doctor
    cd gallery/gallery
    flutter pub get
    flutter build apk
