# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    mkdir -p /home/vsts/.android
    echo 'count=0' > /home/vsts/.android/repositories.cfg
    wget https://dl.google.com/android/repository/sdk-tools-linux-4333796.zip
    mkdir android-sdk-tools
    unzip -qq sdk-tools-linux-4333796.zip -d android-sdk-tools
    Write-Host "##vso[task.setvariable variable=PATH;]`pwd`/android-sdk-tools/tools/bin"
    mkdir -p /opt/android
    yes | sdkmanager --sdk_root=/opt/android "tools" "build-tools;29.0.2" "extras;android;m2repository" > /dev/null
    echo "export PATH=/opt/android/tools/bin:$PATH" >> /etc/profile
    sdkmanager --list
    echo $PATH
  displayName: 'Prepare android sdk'

- script: |
    git clone https://github.com/flutter/flutter.git -b master
    sudo echo "export PATH=./flutter/bin:$PATH" >> /etc/profile
    flutter doctor -v
    echo $PATH
  displayName: 'prepare flutter'

- checkout: self

- script: |
    echo $PATH
    flutter
    flutter pub get
    flutter build apk
  workingDirectory: ./gallery/gallery/
  displayName: 'Build apk'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Pipeline.Workspace)'
    publishLocation: 'pipeline'
