# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    mkdir -p /home/vsts/.android
    echo 'count=0' > /home/vsts/.android/repositories.cfg
    wget https://dl.google.com/android/repository/sdk-tools-linux-4333796.zip
    mkdir android-sdk-tools
    unzip -qq sdk-tools-linux-4333796.zip -d android-sdk-tools
    export PATH=`pwd`/android-sdk-tools/tools/bin:$PATH
    mkdir -p /opt/android
    printf "yes" | sdkmanager --sdk_root=/opt/android "tools" "build-tools;29.0.2" "extras;android;m2repository" > /dev/null
    export PATH=/opt/android/tools/bin:$PATH
    sdkmanager --list
    echo $PATH
  displayName: 'Prepare android sdk'

- checkout: self

- script: |
    git clone https://github.com/flutter/flutter.git -b stable
    export PATH=./flutter/bin:$PATH
    flutter doctor -v
    cd gallery/gallery
    flutter
    flutter pub get
    flutter build apk
  displayName: 'Build apk'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Pipeline.Workspace)'
    publishLocation: 'pipeline'
